// app/components/compound/ProjectCard.vue
<script setup lang="ts">
import type { ProjectSummary } from '@/types/content'

interface Props {
  project: ProjectSummary
}

defineProps<Props>()
</script>

<template>
  <BaseBubble variant="card" hoverable as="article">
    <NuxtLink :to="`/projects/${project.slug}`" class="group mb-2 block">
      <h3 class="text-lg font-semibold text-text-primary-light transition-colors group-hover:text-accent-lavender-light dark:text-text-primary-dark dark:group-hover:text-accent-lavender-dark">
        {{ project.title }}
      </h3>
    </NuxtLink>

    <p class="text-muted mb-4 grow text-sm">
      {{ project.description }}
    </p>

    <div class="mt-4 flex flex-wrap gap-2">
      <BaseBadge v-for="tech in project.technologies" :key="tech.id" :label="tech.label" :icon-id="tech.id" />
    </div>

    <div class="mt-2 flex items-center gap-4 border-t border-border-light pt-3 dark:border-border-dark">
      <a
        v-if="project.githubUrl"
        :href="project.githubUrl"
        target="_blank"
        rel="noopener noreferrer"
        class="link-muted"
        :aria-label="`View ${project.title} on GitHub`"
      >
        <Icon name="github" class="size-4" aria-hidden="true" />
        <span>Code</span>
      </a>

      <a
        v-if="project.liveUrl"
        :href="project.liveUrl"
        target="_blank"
        rel="noopener noreferrer"
        class="link-muted"
        :aria-label="`View ${project.title} live demo`"
      >
        <Icon name="ext" class="size-4" aria-hidden="true" />
        <span>Demo</span>
      </a>

      <NuxtLink :to="`/projects/${project.slug}`" class="link-muted ml-auto">
        <span>Details</span>
        <Icon name="arrow" class="size-4" aria-hidden="true" />
      </NuxtLink>
    </div>
  </BaseBubble>
</template>

// src/components/compound/ProjectCard.tsx
import { FaExternalLinkAlt, FaGithub } from 'react-icons/fa';
import type { Project } from '@/types';
import { Bubble, TechBadge } from '@/components/ui';
import { cn } from '@/lib/utils';

interface ProjectCardProps {
    project: Project;
    className?: string;
}

/**
 * ProjectCard component displays a project preview
 * Shows title, description, technologies, and links with hover animation
 */
export function ProjectCard({ project, className }: ProjectCardProps) {
    return (
        <Bubble variant="card" hoverable as="article" className={cn(className)}>
            {/* Title */}
            <h3 className="text-lg font-semibold text-text-primary-light dark:text-text-primary-dark mb-2">
                {project.title}
            </h3>

            {/* Description */}
            <p className="text-muted text-sm mb-4 grow">{project.description}</p>

            {/* Technologies using TechBadge */}
            <div className="flex flex-wrap gap-2 mb-4">
                {project.technologies.map((tech) => (
                    <TechBadge key={tech} name={tech} />
                ))}
            </div>

            {/* Links */}
            <div className="flex items-center gap-4 mt-auto pt-3 border-t border-border-light dark:border-border-dark">
                {project.githubUrl && (
                    <a
                        href={project.githubUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="link-muted"
                        aria-label={`View ${project.title} on GitHub`}
                    >
                        <FaGithub className="w-4 h-4" />
                        <span>Code</span>
                    </a>
                )}
                {project.liveUrl && (
                    <a
                        href={project.liveUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="link-muted"
                        aria-label={`View ${project.title} live demo`}
                    >
                        <FaExternalLinkAlt className="w-3.5 h-3.5" />
                        <span>Demo</span>
                    </a>
                )}
            </div>
        </Bubble>
    );
}
