// app/components/compound/SkillBubble.vue
<script setup lang="ts">
import type { SkillGroupItem } from '@/types/site'

interface Props {
  group: SkillGroupItem
}

defineProps<Props>()
</script>

<template>
  <BaseBubble>
    <h3
      class="mb-3 text-xs font-semibold tracking-wider text-accent-lavender-light uppercase dark:text-accent-lavender-dark"
    >
      {{ group.label }}
    </h3>

    <div class="flex flex-wrap gap-2">
      <BaseBadge v-for="skill in group.skills" :key="skill.id" :label="skill.name" />
    </div>
  </BaseBubble>
</template>

// src/components/compound/SkillBubble.tsx
import type { SkillGroup } from '@/types';
import { Bubble } from '@/components/ui';
import { TechBadge } from '@/components/ui';

interface SkillBubbleProps {
    group: SkillGroup;
}

/**
 * SkillBubble component displays a skill category with its technologies
 * Used within SkillsSection to group related skills
 */
export function SkillBubble({ group }: SkillBubbleProps) {
    return (
        <Bubble>
            {/* Category label */}
            <h3 className="text-xs font-semibold text-accent-lavender-light dark:text-accent-lavender-dark uppercase tracking-wider mb-3">
                {group.label}
            </h3>

            {/* Skills as flex-wrap pills */}
            <div className="flex flex-wrap gap-2">
                {group.skills.map((skill) => (
                    <TechBadge key={skill.id} name={skill.name} />
                ))}
            </div>
        </Bubble>
    );
}
