// app/components/sections/home/InterestsSection.vue
<script setup lang="ts">
const { data: interests } = await useInterestsContent()
</script>

<template>
  <section class="py-12" aria-labelledby="interests-heading">
    <h2 id="interests-heading" class="section-title">
      Interests
    </h2>

    <div class="flex flex-wrap gap-3">
      <BaseBadge v-for="interest in interests" :key="interest.label" :label="interest.label" />
    </div>
  </section>
</template>

// react-port/src/components/sections/InterestsSection.tsx
import { Badge } from '@/components/ui';
import { cn } from '@/lib/utils';
import { INTERESTS } from '@/data';

interface InterestsSectionProps {
    className?: string;
}

export function InterestsSection({ className }: InterestsSectionProps) {
    return (
        <section className={cn('py-12', className)} aria-labelledby="interests-heading">
            <h2 id="interests-heading" className="section-title">
                Interests
            </h2>

            <div className="flex flex-wrap gap-3">
                {INTERESTS.map((interest) => (
                    <Badge key={interest.label} label={interest.label} />
                ))}
            </div>
        </section>
    );
}
