// app/components/sections/home/HeroSection.vue
<template>
  <section aria-labelledby="hero-heading">
    <h2 class="section-title">
      Me, Myself and I
    </h2>

    <BaseBubble variant="hero">
      <div class="flex flex-col items-center gap-8 text-center md:flex-row md:items-center md:text-left">
        <BaseAvatar src="/rei.webp" alt="Piioni's profile picture" size="xl" class="shrink-0" />

        <div class="space-y-3">
          <h1 id="hero-heading" class="text-primary text-2xl font-bold md:text-3xl">
            Hi! I am
            <span class="text-accent-lavender-light dark:text-accent-lavender-dark"> Juan ツ</span>
          </h1>

          <p class="text-muted max-w-2xl leading-relaxed">
            I am a full stack developer, I love coding and creating new things.
          </p>

          <p class="text-muted text-sm">
            My main tech stack is
            <span class="font-medium text-accent-lavender-light dark:text-accent-lavender-dark">React</span>,
            <span class="font-medium text-accent-lavender-light dark:text-accent-lavender-dark">TypeScript</span>
            and
            <span class="font-medium text-accent-lavender-light dark:text-accent-lavender-dark">Tailwind</span>.
          </p>

          <p class="text-muted text-sm">
            I enjoy Docker and DevOps practices, always looking for ways to improve deployment workflows and CI/CD
            pipelines.
          </p>

          <p class="text-muted text-sm">
            I like music and digital art as well, check out my playlists at
            <a
              href="https://tidal.com/@piioni"
              target="_blank"
              rel="noopener noreferrer"
              class="font-medium text-accent-lavender-light hover:underline dark:text-accent-lavender-dark"
            >
              Tidal profile
            </a>.
          </p>

          <p class="text-muted text-sm">
            You can find my resume here:
            <a
              href="/resume.pdf"
              target="_blank"
              rel="noopener noreferrer"
              class="font-medium text-accent-lavender-light hover:underline dark:text-accent-lavender-dark"
            >
              Resume PDF
            </a>
          </p>
        </div>
      </div>
    </BaseBubble>
  </section>
</template>

// src/components/sections/HeroSection.tsx
import profile_picture from '@/assets/rei.webp';
import { Avatar, Bubble } from '@/components/ui';

export function HeroSection() {
    return (
        <section aria-labelledby="hero-heading">
            <h2 className="section-title">Me, Myself and I</h2>

            <Bubble variant="hero">
                <div className="flex flex-col items-center text-center md:flex-row md:items-center md:text-left gap-8">
                    <Avatar src={profile_picture} alt="Piioni's profile picture" size="xl" className="shrink-0" />

                    <div className="space-y-3">
                        <h1 id="hero-heading" className="text-2xl md:text-3xl font-bold text-primary">
                            Hi! I am <span className="text-accent-lavender">Juan ツ</span>
                        </h1>

                        <p className="text-muted max-w-2xl leading-relaxed">
                            I am a full stack developer, I love coding and creating new things.
                        </p>

                        <p className="text-muted text-sm">
                            My main tech stack is <span className="text-accent-lavender font-medium">React</span>,{' '}
                            <span className="text-accent-lavender font-medium">TypeScript</span> and{' '}
                            <span className="text-accent-lavender font-medium">Tailwind</span>.
                        </p>

                        <p className="text-muted text-sm">
                            I enjoy Docker and DevOps practices, always looking for ways to improve deployment workflows
                            and CI/CD pipelines.
                        </p>

                        <p className="text-muted text-sm">
                            I like music and digital art as well, check out my playlists at{' '}
                            <a
                                href="https://tidal.com/@piioni"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-accent-lavender font-medium hover:underline"
                            >
                                Tidal profile
                            </a>
                            .
                        </p>

                        <p className="text-muted text-sm">
                            You can find my resume here:{' '}
                            <a
                                href="/resume.pdf"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-accent-lavender font-medium hover:underline"
                            >
                                Resume PDF
                            </a>
                        </p>
                    </div>
                </div>
            </Bubble>
        </section>
    );
}
