// app/components/sections/home/SkillsSection.vue
<script setup lang="ts">
import { SKILL_GROUPS } from '@/data/site'

const topRow = computed(() => SKILL_GROUPS.filter(group => group.category === 'frontend' || group.category === 'backend'))
const bottomRow = computed(() => SKILL_GROUPS.filter(group => ['database', 'devtools', 'os'].includes(group.category)))
</script>

<template>
  <section class="py-12" aria-labelledby="skills-heading">
    <h2 id="skills-heading" class="section-title">
      Skills
    </h2>

    <div class="mb-4 grid w-full grid-cols-1 gap-4 md:grid-cols-2">
      <CompoundSkillBubble v-for="group in topRow" :key="group.category" :group="group" />
    </div>

    <div class="grid grid-cols-1 gap-4 md:grid-cols-3">
      <CompoundSkillBubble v-for="group in bottomRow" :key="group.category" :group="group" />
    </div>
  </section>
</template>

// src/components/sections/SkillsSection.tsx
import { SKILL_GROUPS } from '@/data';
import { SkillBubble } from '@/components/compound';
import { cn } from '@/lib/utils';

interface SkillsSectionProps {
    className?: string;
}

/**
 * SkillsSection displays technical skills in a 2-row layout
 * Row 1: Frontend + Backend (larger categories)
 * Row 2: Database + Dev Tools + OS (smaller categories)
 */
export function SkillsSection({ className }: SkillsSectionProps) {
    // Separate groups into rows
    const topRow = SKILL_GROUPS.filter((g) => g.category === 'frontend' || g.category === 'backend');
    const bottomRow = SKILL_GROUPS.filter(
        (g) => g.category === 'database' || g.category === 'devtools' || g.category === 'os'
    );

    return (
        <section className={cn('py-12', className)} aria-labelledby="skills-heading">
            <h2 id="skills-heading" className="section-title">
                Skills
            </h2>

            {/* Top row: Frontend + Backend (2 columns, full width) */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4 w-full">
                {topRow.map((group) => (
                    <SkillBubble key={group.category} group={group} />
                ))}
            </div>

            {/* Bottom row: Database + Dev Tools + OS (3 columns) */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {bottomRow.map((group) => (
                    <SkillBubble key={group.category} group={group} />
                ))}
            </div>
        </section>
    );
}
