// src/pages/Projects.tsx
import { Container } from '@/components/ui';
import { ProjectCard } from '@/components/compound';
import { PROJECTS } from '@/data';

export default function Projects() {
    return (
        <Container>
            <section className="py-8">
                <h1 className="text-3xl font-bold text-text-primary-light dark:text-text-primary-dark mb-8">
                    Projects
                </h1>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {PROJECTS.map((project) => (
                        <ProjectCard key={project.id} project={project} />
                    ))}
                </div>
            </section>
        </Container>
    );
}

// app/pages/projects/index.vue
<script setup lang="ts">
const { data: projects } = await useProjectsContent()
</script>

<template>
  <BaseContainer>
    <section>
      <BasePageHeading title="Projects" subtitle="A curated list of work, experiments and production-ready apps." />

      <div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
        <CompoundProjectCard v-for="project in projects" :key="project.id" :project="project" />
      </div>
    </section>
  </BaseContainer>
</template>
