// src/components/ui/Badge.tsx
import { cn } from '@/lib/utils';
import { getIconConfig } from '@/lib/iconConfig';

interface BadgeProps {
    label: string;
    className?: string;
}

/**
 * Badge component displays a label with icon
 * Used for displaying technologies, interests, and tags
 */
export function Badge({ label, className }: BadgeProps) {
    const { icon: Icon, color: iconColor } = getIconConfig(label);

    return (
        <span
            className={cn(
                'inline-flex items-center gap-2 px-4 py-2 rounded-full',
                'bg-surface border-themed',
                'text-sm font-medium text-primary',
                'transition-all duration-300 ease-smooth',
                'hover:border-accent-lavender-light dark:hover:border-accent-lavender-dark hover:scale-105',
                className
            )}
        >
            {Icon && <Icon className="w-4 h-4 shrink-0" style={{ color: iconColor }} />}
            <span>{label}</span>
        </span>
    );
}

// app/components/base/Badge.vue
<script setup lang="ts">
import { getIconMeta } from '@/utils/icons'

interface Props {
  label: string
}

const props = defineProps<Props>()
const icon = computed(() => getIconMeta(props.label))
</script>

<template>
  <span
    class="inline-flex items-center gap-2 rounded-full bg-surface px-4 py-2 text-sm font-medium text-primary border-themed transition-all duration-300 ease-[var(--ease-smooth)] hover:scale-105 hover:border-accent-lavender-light dark:hover:border-accent-lavender-dark"
  >
    <Icon :name="icon.name" class="size-4 shrink-0" :style="{ color: icon.color }" />
    <span>{{ label }}</span>
  </span>
</template>
